browser=chrome
url=https://staging-admin.gamewyze.com/
login.email.xpath=//input[@id="email"]
login.password.xpath=//input[@id="password"]
login.submit.xpath=//button[@class="login-button"]
username=testezeiatech@gmail.com
passw=Abcd@123
createtournament.menu.xpath=//button[text()='Create Tournament']
createtournament.starttime.xpath=//input[@placeholder="MM/DD/YYYY hh:mm aa"]
createtournament.teamlist.xpath=//ul[@class="MuiList-root MuiList-padding MuiMenu-list css-ubifyk"]/li
createtournament.matchduration.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[2]
createtournament.selectformat.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[3]
createtournament.maxplayers.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[5]
createtournament.submit.xpath=//button[text()="Create Tournament"]
time.starttime=02/03/2026 05:48 PM
selectteam=Knight chess
duration=4
selectformat=rapid
maxplayers=8
switchtotrainer.xpath=//button[text()="Switch to Trainer"]
createtournament.selectdd.xpath=//div[@class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-mp9f0v"]
addtrainer.trainermanagement.xpath=//button[text()="Trainer Management"]
addtrainer.trainer.xpath=//button[text()="Add Trainer"]
addtrainer.name.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[1]
addtrainer.email.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[2]
addtrainer.phonenumber.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[3]
addtrainer.password.xpath=//input[@type="password"]
addtrainer.name=piyush
addtrainer.email=testpiyush123@gmail.com
addtrainer.phonenumber=6666666660
addtrainer.password=Abcd@123
addtrainer.addbutton.xpath=//button[text()="Add"]
addtrainer.delete.xpath=(//button[@style="background: red; color: white; border: none; padding: 6px 10px; border-radius: 5px; cursor: pointer;"])[1]
addteam.menu.xpath=//button[text()="Add Team"]
addteam.enterteamname.xpath=//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"]
addteam.createteam.xpath=//button[text()="Create Team"]
addteam.teamName=chesswess
addteam.submitbutton.xpath=//button[text()="Add"]
addteam.deleteteam.xpath=.//button[@style="background: red; color: white; border: none; padding: 6px 10px; border-radius: 5px; cursor: pointer;"]
addteam.selectoneteam.xpath=(//button[@style="background: red; color: white; border: none; padding: 6px 10px; border-radius: 5px; cursor: pointer;"])
membermanagement.menu.xpath=//button[text()="Member Management"]
membermanagement.addnewuser.xpath=//button[text()="+ Add New User"]
membermanagement.addnewuser.name.xpath=(//input[@type="text"])[2]
membermanagement.addnewuser.name=automationtest
membermanagement.addnewuser.phone.xpath=(//input[@type="text"])[3]
membermanagement.addnewuser.phone= 4343434343
membermanagement.teamlist.xpath=//ul/li[@role="option"]
membermanagement.addnewuser.submit.xpath=(//button[@type="button"])[4]
membermanagement.selectteam.xpath=//div[@role="combobox"]
membermanagement.addnewuser.teamName=Rook Rulers







