browser=chrome
url=https://staging-admin.gamewyze.com/
login.email.xpath=//input[@id="email"]
login.password.xpath=//input[@id="password"]
login.submit.xpath=//button[@class="login-button"]
username=testezeiatech@gmail.com
passw=Abcd@123
createtournament.menu.xpath=//button[text()='Create Tournament']
createtournament.starttime.xpath=//input[@placeholder="MM/DD/YYYY hh:mm aa"]
createtournament.teamlist.xpath=//ul[@class="MuiList-root MuiList-padding MuiMenu-list css-ubifyk"]/li
createtournament.matchduration.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[2]
createtournament.selectformat.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[3]
createtournament.maxplayers.xpath=(//input[@class="MuiInputBase-input MuiOutlinedInput-input css-1pk1fka"])[5]
createtournament.submit.xpath=//button[text()="Create Tournament"]
time.starttime=01/16/2026 7:50 PM
selectteam=Rook Rulers
duration=2
selectformat=rapid
maxplayers=4
switchtotrainer.xpath=//button[text()="Switch to Trainer"]
createtournament.selectdd.xpath=//div[@class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-mp9f0v"]